on:
  push:
    branches:
      - main
name: release-please
jobs:
  # check, test, format and clippy in one step
  prepublish:
    name: pre-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libusb-1.0-0-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check -- --all-targets
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  release-please:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libusb-1.0-0-dev
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          command: publish -- --locked --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
